[2025-05-24 22:35:12,037][asyncio][DEBUG] - Using selector: EpollSelector
[2025-05-24 22:35:12,987][omni.kit.telemetry.impl.sentry_extension][INFO] - sentry is disabled for external build
[2025-05-24 22:35:12,987][omni.kit.telemetry.impl.sentry_extension][INFO] - sentry is disabled for external build
[2025-05-24 22:35:14,373][AutoNode][DEBUG] - Defining data type 'any' as 'Any'
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'bool' as 'Bool' and array 'BoolArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'bundle' as 'Bundle'
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'colord[3]' as 'Color3d' and array 'Color3dArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'colorf[3]' as 'Color3f' and array 'Color3fArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'colorh[3]' as 'Color3h' and array 'Color3hArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'colord[4]' as 'Color4d' and array 'Color4dArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'colorf[4]' as 'Color4f' and array 'Color4fArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'colorh[4]' as 'Color4h' and array 'Color4hArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'double' as 'Double' and array 'DoubleArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'double[2]' as 'Double2' and array 'Double2Array
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'double[3]' as 'Double3' and array 'Double3Array
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'double[4]' as 'Double4' and array 'Double4Array
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'execution' as 'Execution'
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'float' as 'Float' and array 'FloatArray
[2025-05-24 22:35:14,374][AutoNode][DEBUG] - Defining data type 'float[2]' as 'Float2' and array 'Float2Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'float[3]' as 'Float3' and array 'Float3Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'float[4]' as 'Float4' and array 'Float4Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'frame[4]' as 'Frame' and array 'FrameArray
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'half' as 'Half' and array 'HalfArray
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'half[2]' as 'Half2' and array 'Half2Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'half[3]' as 'Half3' and array 'Half3Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'half[4]' as 'Half4' and array 'Half4Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'int' as 'Int' and array 'IntArray
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'int[2]' as 'Int2' and array 'Int2Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'int[3]' as 'Int3' and array 'Int3Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'int[4]' as 'Int4' and array 'Int4Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'int64' as 'Int64' and array 'Int64Array
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'matrixd[2]' as 'Matrix2d' and array 'Matrix2dArray
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'matrixd[3]' as 'Matrix3d' and array 'Matrix3dArray
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'matrixd[4]' as 'Matrix4d' and array 'Matrix4dArray
[2025-05-24 22:35:14,375][AutoNode][DEBUG] - Defining data type 'normald[3]' as 'Normal3d' and array 'Normal3dArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'normalf[3]' as 'Normal3f' and array 'Normal3fArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'normalh[3]' as 'Normal3h' and array 'Normal3hArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'objectId' as 'ObjectId' and array 'ObjectIdArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'path' as 'Path'
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'pointd[3]' as 'Point3d' and array 'Point3dArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'pointf[3]' as 'Point3f' and array 'Point3fArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'pointh[3]' as 'Point3h' and array 'Point3hArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'quatd[4]' as 'Quatd' and array 'QuatdArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'quatf[4]' as 'Quatf' and array 'QuatfArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'quath[4]' as 'Quath' and array 'QuathArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'string' as 'String'
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'target' as 'Target'
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'texcoordd[2]' as 'TexCoord2d' and array 'TexCoord2dArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'texcoordf[2]' as 'TexCoord2f' and array 'TexCoord2fArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'texcoordh[2]' as 'TexCoord2h' and array 'TexCoord2hArray
[2025-05-24 22:35:14,376][AutoNode][DEBUG] - Defining data type 'texcoordd[3]' as 'TexCoord3d' and array 'TexCoord3dArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'texcoordf[3]' as 'TexCoord3f' and array 'TexCoord3fArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'texcoordh[3]' as 'TexCoord3h' and array 'TexCoord3hArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'timecode' as 'Timecode' and array 'TimecodeArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'token' as 'Token' and array 'TokenArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'uchar' as 'UChar' and array 'UCharArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'uint' as 'UInt' and array 'UIntArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'uint64' as 'UInt64' and array 'UInt64Array
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'vectord[3]' as 'Vector3d' and array 'Vector3dArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'vectorf[3]' as 'Vector3f' and array 'Vector3fArray
[2025-05-24 22:35:14,377][AutoNode][DEBUG] - Defining data type 'vectorh[3]' as 'Vector3h' and array 'Vector3hArray
[2025-05-24 22:35:19,490][omni.kit.profiler.window][WARNING] - remove _SpanInstance.__lt__ and use insort 'key' arg instead
[2025-05-24 22:35:24,351][git.cmd][DEBUG] - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/alesr/Repositories/Omnidrones-PEG, stdin=None, shell=False, universal_newlines=False)
[2025-05-24 22:35:24,385][urllib3.connectionpool][DEBUG] - Starting new HTTPS connection (1): api.wandb.ai:443
[2025-05-24 22:35:25,565][urllib3.connectionpool][DEBUG] - Starting new HTTPS connection (1): api.wandb.ai:443
[2025-05-24 22:35:27,632][urllib3.connectionpool][DEBUG] - Starting new HTTPS connection (1): api.wandb.ai:443
[2025-05-24 22:35:27,634][wandb.sdk.lib.retry][ERROR] - Retry attempt failed:
Traceback (most recent call last):
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/alesr/anaconda3/envs/sim_peg/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x75acd23c2140>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/exts/omni.pip.cloud/pip_prebundle/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/kit/exts/omni.kit.pip_archive/pip_prebundle/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x75acd23c2140>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alesr/anaconda3/envs/sim_peg/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/alesr/anaconda3/envs/sim_peg/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/alesr/anaconda3/envs/sim_peg/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/alesr/anaconda3/envs/sim_peg/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/alesr/anaconda3/envs/sim_peg/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/exts/omni.pip.cloud/pip_prebundle/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/exts/omni.pip.cloud/pip_prebundle/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/exts/omni.pip.cloud/pip_prebundle/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/exts/omni.pip.cloud/pip_prebundle/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/alesr/.local/share/ov/pkg/isaac-sim-4.1.0/exts/omni.pip.cloud/pip_prebundle/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x75acd23c2140>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))
[2025-05-24 22:35:29,405][git.cmd][DEBUG] - Popen(['git', 'cat-file', '--batch-check'], cwd=/home/alesr/Repositories/Omnidrones-PEG, stdin=<valid stream>, shell=False, universal_newlines=False)
[2025-05-24 22:35:32,349][urllib3.connectionpool][DEBUG] - Starting new HTTPS connection (1): api.wandb.ai:443
[2025-05-24 22:35:41,125][urllib3.connectionpool][DEBUG] - Starting new HTTPS connection (1): api.wandb.ai:443
